# This file may be used to create an environment using:
# $ conda env create -f environment.yml
# platform: macos-64
# The environment is used for the follwoing notebooks:
# Adversarial_classifier_undersampled_females.ipynb

name: fairness-in-ml_tf1.1
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipython
  - jedi
  - jupyter
  - tensorflow=2.0
  - matplotlib
  - notebook
  - pandas=1.2
  - pip
  - python=3
  - scikit-learn=0.24
  - seaborn
  - pytorch
  - dice-ml


